[package]
name = "workspace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
domain.workspace = true
errors.workspace = true
kernel-store.workspace = true
sandbox.workspace = true

[dev-dependencies]
kernel-store-sqlite.workspace = true
tempfile.workspace = true
testkit.workspace = true
tokio.workspace = true
