[package]
name = "process-supervisor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
adapter-protocol.workspace = true
domain.workspace = true
errors.workspace = true
kernel-store.workspace = true
prost.workspace = true
rustix.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
testkit.workspace = true
kernel-store-sqlite.workspace = true
